export const ErrorType = {
    FILE_IMPORT: "FILE_IMPORT",
    DATA_PARSE: "DATA_PARSE",
    ANALYSIS: "ANALYSIS",
    CHART: "CHART",
    EXPORT_EXCEL: "EXPORT_EXCEL",
    EXPORT_PDF: "EXPORT_PDF",
    STORAGE: "STORAGE",
    WORKER: "WORKER",
    VUE_ERROR: "VUE_ERROR",
    UNKNOWN: "UNKNOWN"
}