/**
 * RNA模板ID生成器
 *
 * 统一样本ID生成格式，确保所有地方生成的ID格式一致。
 * 格式：YYYYMMDD_XXX（年月日_三位序号）
 */


/**
 * 生成模板ID
 *
 * @param {number} index 序号（从1开始）
 * @returns {string} 模板ID，如 20260713_001
 */
export function generateTemplateId(index = 1) {
    const date = new Date();

    const y = date.getFullYear();
    const m = String(date.getMonth() + 1).padStart(2, "0");
    const d = String(date.getDate()).padStart(2, "0");

    return `${y}${m}${d}_${String(index).padStart(3, "0")}`;
}


/**
 * 获取日期字符串（YYYYMMDD格式）
 *
 * @returns {string} 日期字符串
 */
export function getDateString() {
    const d = new Date();

    const y = d.getFullYear();
    const m = String(d.getMonth() + 1).padStart(2, "0");
    const day = String(d.getDate()).padStart(2, "0");

    return `${y}${m}${day}`;
}


/**
 * 验证ID是否为自动生成格式
 *
 * @param {string} id 模板ID
 * @returns {boolean} 是否为自动生成格式
 */
export function isAutoGeneratedId(id) {
    const pattern = /^\d{8}_\d{3}$/;
    return pattern.test(id);
}
