/**
 * RNA质量判断 - 核心逻辑统一入口
 *
 * 所有模块应从此处导入核心函数，而不是直接导入子模块。
 * 这样做的好处：
 * 1. 统一入口，便于管理和维护
 * 2. 修改内部实现时，外部调用无需改动
 * 3. 便于做版本控制和向后兼容
 *
 * 示例：
 *   import {
 *     getValidSamples,
 *     analyzeRNA,
 *     generateTemplateId
 *   } from "@/core";
 */

// ===== 样本处理 =====
export {
    getValidSamples,
    getSampleCount,
    isEmptySample,
    getNumber,
    isPresent
} from "./sample/sampleUtils";

export {
    generateTemplateId,
    getDateString,
    isAutoGeneratedId
} from "./sample/idGenerator";


// ===== 质量分析 =====
export {
    analyzeRNA
} from "./quality";


// ===== 污染分析 =====
export {
    analyzePollution
} from "./pollution/pollutionAnalyzer";


// ===== 建议生成 =====
export {
    judgePollution,
    getExtractionAdvice,
    getConcentrationAdvice,
    generateAdvice
} from "./advice";


// ===== 统计 =====
export {
    getSampleStatistics,
    getPollutionStatistics,
    getExtractionStatistics
} from "./statistics";


// ===== 报告格式化 =====
export {
    formatPollutionText,
    formatAdviceText,
    formatExtractionProblemText,
    formatExtractionSuggestionText,
    getPollutionLevelLabel
} from "./export/formatReportData";
